# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

use_frameworks!
target 'SocialSDKs_Swift' do
  # Comment the next line if you don't want to use dynamic frameworks

  # Pods for SocialSDKs_Swift
  pod 'SocialSDKs_Swift_ReducedWeChat', :path => '../'
#  pod 'SocialSDKs_Swift_WeChat', :path => '../'
  pod 'SocialSDKs_Swift_TencentQQ', :path => '../'
  pod 'SocialSDKs_Swift_Weibo', :path => '../'
  pod 'SocialSDKs_Swift_WeiboSDKBundle', :path => '../'
end
